builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
universal_binaries:
  - id: frigg
    ids:
      - build1
      - build2
brews:
  - name: frigg
    homepage: "https://github.com/PatrickLaabs/frigg"
    repository:
      owner: PatrickLaabs
      name: frigg
    commit_author:
      name: PatrickLaabs
      email: patrick.laabs@me.com