builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
brews:
  - name: frigg
    homepage: "https://github.com/PatrickLaabs/frigg"
    tap:
      owner: PatrickLaabs
      name: homebrew-patricklaabs
    commit_author:
      name: PatrickLaabs
      email: patrick.laabs@me.com