version: '3'

tasks:
  build:
    cmds:
      - go build -o ../frigg main.go

  testsuite_capd_controller:
    cmds:
      - ./main version
      - ./main testsuite capd_controllertest

  destroy_testsuite:
    cmds:
      - ./main delete clusters -A