---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: argo-workflows
spec:
  clusterSelector:
    matchLabels:
      argo-workflows-Enabled: default
  repoURL: https://argoproj.github.io/argo-helm
  chartName: argo-workflows
  namespace: argocd
  releaseName: argo-workflows
  version: 0.40.5
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: false
  valuesTemplate: |
    workflow:
      serviceAccount:
        create: true
        name: "argocd-workflow"
      rbac:
        create: true
    controller:
      rbac:
        create: true
        accessAllSecrets: true
      workflowNamespaces:
        - argo
    extraObjects:
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: argocd-workflow-cluster
        rules:
        - apiGroups: ["cluster.x-k8s.io"]
          resources: ["clusters"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["infrastructure.cluster.x-k8s.io"]
          resources: ["vsphereclusters", "azureclusters", "dockerclusters"]
          verbs: ["get", "list", "watch"]
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["get", "list", "watch"]
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: argocd-workflow-cluster
        subjects:
        - kind: ServiceAccount
          name: argocd-workflow
          namespace: argo
        roleRef:
          kind: ClusterRole
          name: argocd-workflow-cluster
          apiGroup: rbac.authorization.k8s.io
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: argo-events-workflows
          namespace: argo
        rules:
        - apiGroups: ["argoproj.io"]
          verbs: ["*"]
          resources: ["workflows", "workflowtemplates"]
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: argocd-events-workflows
          namespace: argo
        subjects:
        - kind: ServiceAccount
          name: argocd-workflow
          namespace: argo
        roleRef:
          kind: Role
          name: argo-events-workflows
          apiGroup: rbac.authorization.k8s.io
    server:
      extraArgs:
      - --auth-mode=server
      - --auth-mode=client
      sso:
        enabled: false
      secure: false
      ingress:
        enabled: false
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          cert-manager.io/cluster-issuer: smallstep-acme-http01
          traefik.ingress.kubernetes.io/router.tls: "true"
        ingressclassName: "traefik"
        hosts:
          - argo-workflows-mgmt.localho.st
        paths:
          - /
        pathType: Prefix
        tls:
          - secretName: argo-workflows-tls
            hosts:
              - argo-workflows-mgmt.localho.st