---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: argo-events
spec:
  clusterSelector:
    matchLabels:
      argo-events-Enabled: default
  repoURL: https://argoproj.github.io/argo-helm
  chartName: argo-events
  namespace: argocd
  releaseName: argo-events
  version: 2.4.2
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: false