---
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: vault
spec:
  clusterSelector:
    matchLabels:
      vaultmgmtEnabled: default
  repoURL: https://helm.releases.hashicorp.com
  chartName: vault
  namespace: vault
  releaseName: vault
  version: 0.27.0
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  valuesTemplate: |
    server:
      ha:
        config: |
          ui = true
          listener "tcp" {
            tls_disable     = 1
            address         = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          service_registration "kubernetes" {}
    ui:
      enabled: true
      serviceType: "ClusterIP"
      serviceNodePort: null
      externalPort: 8200
      targetPort: 8200